[package]
name = "vibranium-cli"
version = "0.1.0"
authors = ["Pascal Precht <pascal.precht@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
vibranium = { path = "../" }

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
toml = "0.4.10"
tempfile = "3"
